require:
  - rubocop-rspec

# This is required to allow Exclude below to work during GitHub CI
# See https://github.com/rubocop/rubocop/issues/6567 for additional details
inherit_mode:
  merge:
    - Exclude

AllCops:
  NewCops: enable
  DisplayCopNames: true
  TargetRubyVersion: 3.0
  Exclude:
    - '.idea'
    - '*.iml'
    - 'bin/**/*'
    - 'node_modules/**'
    - 'tmp/**'
    - 'vendor/**'

RSpec:
  Enabled: true

Layout/ArgumentAlignment:
  EnforcedStyle: with_first_argument

Layout/LineLength:
  Max: 140

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Lint/AmbiguousBlockAssociation:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ParameterLists:
  Max: 6

Metrics/PerceivedComplexity:
  Enabled: false

Naming/MemoizedInstanceVariableName:
  Enabled: false

RSpec/AnyInstance:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/ExpectInHook:
  Enabled: false

RSpec/MessageSpies:
  EnforcedStyle: receive

RSpec/MultipleExpectations:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true

Style/HashSyntax:
  EnforcedStyle: ruby19

Style/OpenStructUse:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/SymbolArray:
  Enabled: false

Style/WordArray:
  Enabled: false
